version: "3.3"
services:
  traefik:
    image: "traefik:v2.0.5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./config/rules.toml:/config/rules.toml"
      - "traefik2_data:/etc/traefik/acme"
      - "traefik2_logs:/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      ### traefik dashboard
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=auth-traefik"
      ### global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      ### middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      ### please generate your own password first
      - "traefik.http.middlewares.auth-traefik.basicauth.users=user:$$apsdsdfefsL$$oBR6oU73m0j6GqHCGMrNB."
    networks:
      - proxy_network
############# VOLUMES ###############
volumes:
  traefik2_logs:
  traefik2_data:
############# NETWORKS ##############
networks:
  proxy_network:
    external: true
